server:
  port: 8080

spring:
  profiles:
    active: dev
    include: core, auth, exception, redis
  application:
    name: Z-Blog
  mvc:
    servlet:
      path: /api/
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/zblog
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: jx_zou8023


logging:
  file:
    path: logs
