spring:
  datasource:
    url: jdbc:postgresql://192.168.0.200:5432/zblog
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: jx_zou8023
    hikari:
      allow-pool-suspension: true
  jpa:
    generate-ddl: true