safety:
  rsa:
    size: 2048
  jwt:
    salt:
      size: 20
    access-token:
      expire: 3600
      prefix: "Bearer "
      iss: z-blog
      sub: ZBLOG-USER

captcha:
  code:
    mail:
      size: 6
      expire: 300

spring:
  mvc:
    throw-exception-if-no-handler-found: true
#  messages:
#    basename: classpath:/messages
#    encoding: UTF-8
#  web:
#    locale: zh_CN
